pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r index.html style.css og-image.jpg about posts links public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
