pages:
  stage: deploy
  script:
    - mkdir public
    - tar --exclude='./.git' --exclude='./public' --exclude='./templates' --exclude='./scripts' --exclude='./publish.sh' --exclude='./.gitlab-ci.yml' -cf - . | tar -xf - -C public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
